"""Slot generation: expand weekly availabilities into concrete bookable slots.

Availability wall-clock times are interpreted in the *doctor's clinic timezone*
(``DoctorProfile.timezone``, IANA, default ``Africa/Casablanca``), NOT in UTC. A
09:00 window in Casablanca (UTC+1 in summer) therefore yields an 08:00Z slot.
Slots are generated by stepping the cursor in the doctor's LOCAL wall clock and
converting each ``(start, end)`` to UTC via ``.astimezone(UTC)`` — the API/DB
store and compare UTC-aware instants.

``AvailabilityException`` rows override the recurring weekly schedule on a
specific date: a whole-day ``BLOCK`` removes every slot that day, a timed
``BLOCK`` removes only the overlapping local slots, and an ``OPEN`` adds an
extra one-off window on that date.

Ported from the prototype's tz-aware logic
(``backend/app/services/appointments.py``).
"""

from datetime import UTC, date, datetime, time, timedelta
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from sehaty.db import (
    Appointment,
    AppointmentStatus,
    Availability,
    AvailabilityException,
    AvailabilityExceptionKind,
    DoctorProfile,
)
from sqlalchemy import select
from sqlalchemy.orm import Session

MAX_RANGE_DAYS = 31

# Fallback when a doctor has no profile row (or a blank/unknown timezone).
DEFAULT_TIMEZONE = "Africa/Casablanca"

# Statuses that still occupy a slot (a cancelled/no-show slot frees up again).
ACTIVE_STATUSES = (AppointmentStatus.REQUESTED, AppointmentStatus.CONFIRMED)


def _as_utc(dt: datetime) -> datetime:
    """Normalise a (possibly naive) datetime to UTC-aware."""
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=UTC)
    return dt.astimezone(UTC)


def _doctor_timezone(session: Session, doctor_id: int) -> ZoneInfo:
    """Load the doctor's clinic timezone (column-only, no PostGIS geopoint).

    Defaults to ``Africa/Casablanca`` when the doctor has no profile, a blank
    value, or an unrecognised IANA name.
    """
    tz_name = session.execute(
        select(DoctorProfile.timezone).where(DoctorProfile.user_id == doctor_id)
    ).scalar_one_or_none()
    if not tz_name:
        tz_name = DEFAULT_TIMEZONE
    try:
        return ZoneInfo(tz_name)
    except (ZoneInfoNotFoundError, ValueError):
        return ZoneInfo(DEFAULT_TIMEZONE)


def _booked_starts(
    session: Session, doctor_id: int, from_dt: datetime, to_dt: datetime
) -> set[datetime]:
    """Return the UTC start times of active appointments in ``[from_dt, to_dt)``."""
    rows = session.execute(
        select(Appointment.start_at).where(
            Appointment.doctor_id == doctor_id,
            Appointment.status.in_(ACTIVE_STATUSES),
            Appointment.start_at >= from_dt,
            Appointment.start_at < to_dt,
        )
    ).scalars()
    return {_as_utc(s) for s in rows}


def _exceptions_by_date(
    session: Session, doctor_id: int, from_date: date, to_date: date
) -> dict[date, list[AvailabilityException]]:
    """Load the doctor's availability exceptions in range, grouped by date."""
    rows = (
        session.execute(
            select(AvailabilityException).where(
                AvailabilityException.doctor_id == doctor_id,
                AvailabilityException.date >= from_date,
                AvailabilityException.date <= to_date,
            )
        )
        .scalars()
        .all()
    )
    by_date: dict[date, list[AvailabilityException]] = {}
    for e in rows:
        by_date.setdefault(e.date, []).append(e)
    return by_date


def _overlaps_blocked(
    day: date,
    tz: ZoneInfo,
    slot_start_local: datetime,
    slot_end_local: datetime,
    blocked: list[tuple[time, time]],
) -> bool:
    """True if the local slot overlaps any timed BLOCK window on that date."""
    for bstart, bend in blocked:
        block_start = datetime.combine(day, bstart, tzinfo=tz)
        block_end = datetime.combine(day, bend, tzinfo=tz)
        if slot_start_local < block_end and slot_end_local > block_start:
            return True
    return False


def available_slots(
    session: Session, doctor_id: int, from_date: date, to_date: date
) -> list[tuple[datetime, datetime]]:
    """Return the free ``(start, end)`` UTC slots for a doctor across a range.

    Weekly availabilities are expanded into concrete slots across the inclusive
    ``[from_date, to_date]`` range (capped at ``MAX_RANGE_DAYS``), interpreting
    each window's wall-clock times in the doctor's clinic timezone and returning
    UTC-aware instants. ``AvailabilityException`` rows override the schedule per
    date (whole-day / timed BLOCK, one-off OPEN). Slots already taken by active
    (REQUESTED/CONFIRMED) appointments are removed (compared in UTC).
    """
    if (to_date - from_date).days > MAX_RANGE_DAYS:
        to_date = from_date + timedelta(days=MAX_RANGE_DAYS)

    availabilities = (
        session.execute(select(Availability).where(Availability.doctor_id == doctor_id))
        .scalars()
        .all()
    )
    exceptions = _exceptions_by_date(session, doctor_id, from_date, to_date)
    if not availabilities and not exceptions:
        return []

    by_weekday: dict[int, list[Availability]] = {}
    for a in availabilities:
        by_weekday.setdefault(a.weekday, []).append(a)

    tz = _doctor_timezone(session, doctor_id)

    # Booked-start lookup spans one extra UTC day on each side because a local
    # window near midnight can convert to an adjacent UTC date.
    range_start = datetime.combine(from_date - timedelta(days=1), time.min, tzinfo=UTC)
    range_end = datetime.combine(to_date + timedelta(days=2), time.min, tzinfo=UTC)
    booked = _booked_starts(session, doctor_id, range_start, range_end)

    slots: list[tuple[datetime, datetime]] = []
    day = from_date
    while day <= to_date:
        day_excs = exceptions.get(day, [])

        # Whole-day BLOCK (NULL start/end) → no slots at all that day.
        if any(
            e.kind == AvailabilityExceptionKind.BLOCK
            and e.start_time is None
            and e.end_time is None
            for e in day_excs
        ):
            day += timedelta(days=1)
            continue

        # Candidate windows: recurring weekly + one-off OPEN exceptions.
        windows: list[tuple[time, time, int]] = [
            (a.start_time, a.end_time, a.slot_minutes) for a in by_weekday.get(day.weekday(), [])
        ]
        for e in day_excs:
            if (
                e.kind == AvailabilityExceptionKind.OPEN
                and e.start_time is not None
                and e.end_time is not None
                and e.slot_minutes
            ):
                windows.append((e.start_time, e.end_time, e.slot_minutes))

        # Timed BLOCK windows to subtract on this date.
        blocked = [
            (e.start_time, e.end_time)
            for e in day_excs
            if e.kind == AvailabilityExceptionKind.BLOCK
            and e.start_time is not None
            and e.end_time is not None
        ]

        for start_time, end_time, slot_minutes in windows:
            cursor = datetime.combine(day, start_time, tzinfo=tz)
            end_of_window = datetime.combine(day, end_time, tzinfo=tz)
            step = timedelta(minutes=slot_minutes)
            while cursor + step <= end_of_window:
                slot_end_local = cursor + step
                if not _overlaps_blocked(day, tz, cursor, slot_end_local, blocked):
                    start_utc = cursor.astimezone(UTC)
                    if start_utc not in booked:
                        slots.append((start_utc, slot_end_local.astimezone(UTC)))
                cursor += step

        day += timedelta(days=1)

    slots.sort(key=lambda s: s[0])
    return slots


def find_slot_end(session: Session, doctor_id: int, start_at: datetime) -> datetime | None:
    """Validate a requested start against real availability; return its end.

    Returns the slot's end datetime if ``start_at`` is a genuine free slot for
    the doctor, otherwise ``None`` (outside availability or already booked). The
    scan widens by a day on each side of ``start_at`` so a local window that
    converts to an adjacent UTC date still matches.
    """
    start_at = _as_utc(start_at)
    day = start_at.date()
    for start, end in available_slots(
        session, doctor_id, day - timedelta(days=1), day + timedelta(days=1)
    ):
        if start == start_at:
            return end
    return None
